### PR TITLE
Add subsites for Cabal, GHC, GHCup and stack

### LINKED ISSUE #378: Allow to link to all errors of a specific tool
Follow-up of https://github.com/haskellfoundation/error-message-index/issues/350#issuecomment-1382672906

I'd like to have a link such as https://errors.haskell.org/messages/GHCup that shows all and only GHCup errors.

### PR DESCRIPTION
**Pull request by haglobah**
Fixes #378

### CODE REVIEW

**Review by BinderDavid — APPROVED** [review]
Thanks! That looks great.

**Comment by ulysses4ever** [comment]
These subsites aren't very discoverable, are they? At least, nothing on the main page tells me they exist, as far as I can see.

**Comment by BinderDavid** [comment]
> These subsites aren't very discoverable, are they? At least, nothing on the main page tells me they exist, as far as I can see.

We don't really have a proper landing site, only the site listing all the errors. My thinking was that the subsites can be used by the individual projects (cabal, ghc, stack, ghcup) as link targets from their respective documentation.

**Comment by ulysses4ever** [comment]
Fair enough.

**Pull request merged**
