### PR TITLE
Add docs for tool developers

### PR DESCRIPTION
**Pull request by david-christiansen**
I hope that this addresses the questions from #355.

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]
This is very helpful, thanks!

Some more questions:

I think that this effectively means that _error code assignment_ and _explanation provision_ are coupled: in order to get an error code I have to write an explanation of it. Is there any way for me to get some codes at the cost of some "explanation debt"? Suppose I want to convert all my errors to have codes, but I don't have time to write all the explanations right now, it would be nice to be able to allocate all the codes, and then later add the explanations. Or maybe if I "own" the namespace I can just do this?

Relatedly, I think maybe it would help to have a few user workflows written out. E.g. here's what I think happens if you add a new error:
1. PR to project adding new error, assign error code according to your namespace's allocation strategy (?). No need to do anything to the error index (?).
2. PR is merged to project.
3. Add an explanation to the error index for the new code. Can do this at any time including before (?) or after (?) releasing the software with the new error.

**Comment by david-christiansen** [comment]
I've uploaded a new version of the docs that I hope addresses @michaelpj's questions.

**Review by michaelpj — APPROVED** [review]
Great stuff!

**Comment by david-christiansen** [comment]
Thanks for asking good questions, I'm glad to have the metadocs also improve :-)

**Pull request merged**
